questions = [

["The Name Of Python Developer is Gudio Van Rossum", "true"],
["The Macos Uses Linux as It\'s Os", "false"],
["India Got Independence On 15th August", "true"],
["Sandeep Maheshwari Runs Channel Carry Minati", "false"],
["Subash Chandra Bose Founded Azad Hind Saina", "true"],

[
    "In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.",
    "True"],
["Pluto is a planet.", "False"],
["The average woman is 5 inches / 13 centimeters shorter than the average man.", "True"],
["Did Michael Jackson invent the moonwalk?", "False"],
[
    "SCP-173 was the first SCP article written for the web-based collaborative fiction project known as the 'SCP Foundation'",
    "True"],
["The scientific name for the Southern Lights is Aurora Australis?", "True"],
["'Santa Claus' is a variety of melon.", "True"],
["Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.", "True"],
["The US emergency hotline is 911 because of the September 11th terrorist attacks.", "False"],
["A pasodoble is a type of Italian pasta sauce.", "False"],
["Spoon theory is a theory, utilizing 'Spoons' as a metaphor for energy they can use in a day.", "True"],
[
    "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.",
    "False"],
["Adolf Hitler was born in Australia.", "False"],
["The National Animal of Scotland is the Unicorn.", "True"],
["All strawberries are red.", "False"],
["Video streaming website YouTube was purchased in its entirety by Facebook for US$1.65 billion in stock.", "False"],
["Scotland voted to become an independent country during the referendum from September 2014.", "False"],
["The commercial UK channel ITV stands for 'International Television'.", "False"],
["Pure water effectively conducts electricity", "False"],
["A pencil's lead is typically made from graphite, not lead", "True"],
["The term 'Spam' came before the food product 'Spam'.", "False"],
["Bulls are attracted to the color red.", "False"],
["French is an official language in Canada.", "True"],
["Fast food restaurant chains Carl's Jr. and Hardee's are owned by the same company.", "True"],
["The word 'news' originates from the first letters of the 4 main directions on a compass (North, East, West, South).",
 "False"],
["The French word to travel is 'Travail'", "False"],

["The sum of all the numbers on a roulette wheel is 666.", "True"],
["Haggis is traditionally ate on Burns Night.", "True"],
["Jingle Bells was originally meant for Thanksgiving", "True"],
["Ping-Pong originated in England", "True"],
["The French word for 'glass' is 'glace'.", "False"],
[
    "The pickled gherkin was first added to hamburgers because a US health law required all fast-food to include a source of Vitamin C.",
    "False"],
["The British organisation CAMRA stands for The Campaign for Real Ale.", "True"],
["Albert Einstein had trouble with mathematics when he was in school.", "False"],
["This is the correct spelling of 'Supercalifragilisticexpialidocious'.", "True"],
["Dihydrogen Monoxide is a dangerous chemical.", "False"],
["When you cry in space, your tears stick to your face.", "True"],
["You can legally drink alcohol while driving in Mississippi.", "True"],
["Cucumbers are usually more than 90% water.", "True"],
["The Sun rises from the North.", "False"],
["Crystal Pepsi was first sold in US markets in 1993.", "False"],
["You are allowed to sell your soul on eBay.", "False"],
["The bikini is named after the 'Bikini Atoll', an island where the United States conducted tests on atomic bombs.",
 "True"]
]

film_questions = [
    ["Yash played the lead role in KGF.", "True"],
    ["Baahubali was directed by S. S. Rajamouli.", "True"],
    ["In Baahubali, the role of Bhallaladeva was played by Rana Daggubati.", "True"],
    ["Dangal is based on the life of cricketer M. S. Dhoni.", "False"],
    ["Aamir Khan played the role of Mahavir Singh Phogat in Dangal.", "True"],
    ["RRR won the Oscar for Best Original Song in 2023.", "True"],
    ["The song 'Naatu Naatu' is from the movie Pushpa.", "False"],
    ["Allu Arjun starred in the movie Pushpa.", "True"],
    ["Shah Rukh Khan played a scientist in the movie Swades.", "True"],
    ["The film Lagaan was nominated for an Academy Award.", "True"],
    ["In 3 Idiots, Aamir Khan’s character was named Rancho.", "True"],
    ["Ranbir Kapoor played Sanjay Dutt in the movie Sanju.", "True"],
    ["Salman Khan acted in the movie PK.", "False"],
    ["Hrithik Roshan debuted in the year 2000 with Kaho Naa Pyaar Hai.", "True"],
    ["The movie Chennai Express starred Salman Khan.", "False"],
    ["Deepika Padukone acted in the movie Om Shanti Om.", "True"],
    ["Kabir Singh was played by Shahid Kapoor.", "True"],
    ["The film Gully Boy is based on the life of Virat Kohli.", "False"],
    ["Ranveer Singh starred in Gully Boy.", "True"],
    ["Katrina Kaif acted in the movie Zindagi Na Milegi Dobara.", "True"],
    ["Ajay Devgn played the role of Singham in the movie Singham.", "True"],
    ["The movie Drishyam stars Rajinikanth in the lead role.", "False"],
    ["Vikram Vedha starred Hrithik Roshan in the 2022 remake.", "True"],
    ["Prabhas played the role of Baahubali in Baahubali series.", "True"],
    ["The film Ra.One starred Aamir Khan.", "False"],
    ["Shahid Kapoor acted in Haider, an adaptation of Hamlet.", "True"],
    ["Bajrangi Bhaijaan starred Salman Khan.", "True"],
    ["KGF Chapter 2 was released in 2022.", "True"],
    ["Kabir Khan directed the movie Chak De! India.", "True"],
    ["Shah Rukh Khan played a hockey coach in Chak De! India.", "True"],
    ["M. S. Dhoni: The Untold Story starred Sushant Singh Rajput.", "True"],
    ["PK starred Aamir Khan in an alien role.", "True"],
    ["Salman Khan acted in the movie Jodhaa Akbar.", "False"],
    ["Hrithik Roshan played Akbar in Jodhaa Akbar.", "True"],
    ["Amitabh Bachchan acted as a teacher in the movie Black.", "True"],
    ["Alia Bhatt acted in Raazi, a spy thriller film.", "True"],
    ["RRR starred Ram Charan and Jr. NTR.", "True"],
    ["The movie Pushpa starred Vijay Deverakonda.", "False"],
    ["Bahubali was released before the year 2010.", "False"],
    ["Padmaavat starred Ranveer Singh as Alauddin Khilji.", "True"],
    ["Kabir Singh is a remake of the Telugu movie Arjun Reddy.", "True"],
    ["The movie War starred Hrithik Roshan and Tiger Shroff.", "True"],
    ["Student of the Year (2012) introduced Varun Dhawan, Alia Bhatt, and Sidharth Malhotra.", "True"],
    ["The film Rockstar starred Salman Khan.", "False"],
    ["Ranbir Kapoor starred in the film Rockstar.", "True"],
    ["The movie Barfi starred Ranbir Kapoor and Priyanka Chopra.", "True"],
    ["Shershaah was based on the life of Captain Vikram Batra.", "True"],
    ["Sidharth Malhotra played the role of Vikram Batra in Shershaah.", "True"],
    ["Sooryavanshi was directed by Rohit Shetty.", "True"],
    ["Akshay Kumar played the lead in Sooryavanshi.", "True"]
]
cartoon_questions = [
    ["Doraemon came from the 22nd century.", "True"],
    ["Nobita is very good at studies in Doraemon.", "False"],
    ["Doraemon is a cat-type robot.", "True"],
    ["Shizuka is Nobita’s best female friend.", "True"],
    ["Motu loves to eat samosas.", "True"],
    ["Patlu is smarter than Motlu.", "True"],
    ["Dr. Jhatka is the scientist in Motlu Patlu.", "True"],
    ["Chingam always says 'In Chingam’s raj, crime will not pass'.", "True"],
    ["Ladybug’s real name is Marinette.", "True"],
    ["Cat Noir’s real name is Adrien.", "True"],
    ["Hawk Moth is the villain in Miraculous Ladybug.", "True"],
    ["Pakdam Pakdai is also called Rat-a-Tat.", "True"],
    ["In Pakdam Pakdai, Doggy Don always fights with mice.", "True"],
    ["Colonel is the elder brother of Doggy Don in Pakdam Pakdai.", "True"],
    ["Oggy is a blue cat.", "True"],
    ["Oggy always chases the cockroaches.", "False"],
    ["The cockroaches in Oggy and the Cockroaches are Joey, Dee Dee, and Marky.", "True"],
    ["Joey is the pink cockroach.", "True"],
    ["Grizzy is a bear.", "True"],
    ["The Lemmings are very calm animals in Grizzy and the Lemmings.", "False"],
    ["Oggy has a cousin named Jack.", "True"],
    ["Motu Patlu live in Furfuri Nagar.", "True"],
    ["In Doraemon, Gian loves to sing but sings badly.", "True"],
    ["Suneo always shows off his toys in Doraemon.", "True"],
    ["Marinette loves Adrien in Miraculous Ladybug.", "True"],
    ["Cat Noir uses a power called Cataclysm.", "True"],
    ["Ladybug’s weapon is a yo-yo.", "True"],
    ["Oggy loves to watch TV peacefully.", "True"],
    ["Dee Dee loves to eat all the food in Oggy’s house.", "True"],
    ["In Pakdam Pakdai, the mice are Lambu, Chhotu, and Motu.", "True"],
    ["Colonel is very brave in Pakdam Pakdai.", "True"],
    ["Grizzy tries to stop the Lemmings from creating chaos.", "True"],
    ["Doraemon’s pocket is four-dimensional.", "True"],
    ["Nobita often gets scolded by his mother.", "True"],
    ["Motu gains strength after eating samosas.", "True"],
    ["Patlu usually saves Motlu from trouble.", "True"],
    ["Chingam tries to catch criminals but mostly fails.", "True"],
    ["In Miraculous Ladybug, Alya is Marinette’s best friend.", "True"],
    ["Adrien is also known as Cat Noir.", "True"],
    ["Ladybug and Cat Noir fight together against Hawk Moth.", "True"],
    ["In Oggy and the Cockroaches, Jack often helps Oggy fight cockroaches.", "True"],
    ["The cockroaches in Oggy are friendly to Oggy.", "False"],
    ["Grizzy lives in the forest ranger’s house.", "True"],
    ["The Lemmings always disturb Grizzy.", "True"],
    ["Doraemon’s favorite food is Dorayaki.", "True"],
    ["Shizuka likes playing the violin.", "True"],
    ["Motu and Patlu are inseparable friends.", "True"],
    ["Hawk Moth wants to steal Ladybug and Cat Noir’s Miraculous.", "True"],
    ["Oggy is lazy and loves a peaceful life.", "True"],
    ["In Pakdam Pakdai, Doggy Don is afraid of the mice.", "True"]
]
history_questions = [
    ["Mahatma Gandhi is known as the Father of the Nation of India.", "True"],
    ["India got independence in 1947.", "True"],
    ["Subhas Chandra Bose gave the slogan 'Do or Die'.", "False"],
    ["Bal Gangadhar Tilak said 'Swaraj is my birthright and I shall have it'.", "True"],
    ["Bhagat Singh gave the slogan 'Inquilab Zindabad'.", "True"],
    ["Rani Lakshmibai fought in the Revolt of 1857.", "True"],
    ["The Jallianwala Bagh massacre happened in 1920.", "False"],
    ["The Dandi March was led by Mahatma Gandhi in 1930.", "True"],
    ["The Quit India Movement was launched in 1942.", "True"],
    ["Chandrasekhar Azad died in Allahabad.", "True"],
    ["The Indian National Congress was founded in 1885.", "True"],
    ["Lala Lajpat Rai was also known as 'Punjab Kesari'.", "True"],
    ["The Simon Commission came to India in 1928.", "True"],
    ["Rabindranath Tagore wrote the Indian National Anthem.", "True"],
    ["The First War of Independence happened in 1857.", "True"],
    ["Sardar Vallabhbhai Patel is known as the Iron Man of India.", "True"],
    ["The Partition of Bengal happened in 1905.", "True"],
    ["Bipin Chandra Pal, Lala Lajpat Rai, and Bal Gangadhar Tilak were called 'Lal-Bal-Pal'.", "True"],
    ["The Jallianwala Bagh massacre was ordered by General Dyer.", "True"],
    ["The Non-Cooperation Movement was launched in 1920.", "True"],
    ["Jawaharlal Nehru was the first Prime Minister of India.", "True"],
    ["Subhas Chandra Bose formed the Indian National Army (INA).", "True"],
    ["The Indian Constitution came into effect on 26th January 1950.", "True"],
    ["Lord Mountbatten was the last Viceroy of India.", "True"],
    ["The Revolt of 1857 started from Meerut.", "True"],
    ["Bhagat Singh, Rajguru, and Sukhdev were hanged in 1931.", "True"],
    ["The Swadeshi Movement encouraged the use of foreign goods.", "False"],
    ["Dadabhai Naoroji is known as the 'Grand Old Man of India'.", "True"],
    ["The Battle of Plassey was fought in 1857.", "False"],
    ["The Battle of Panipat was fought three times in Indian history.", "True"],
    ["Tipu Sultan was known as the 'Tiger of Mysore'.", "True"],
    ["Chittaranjan Das was a leader of the Swaraj Party.", "True"],
    ["The Kakori Train Robbery took place in 1925.", "True"],
    ["The Rowlatt Act was passed in 1919.", "True"],
    ["The Poona Pact was signed between B.R. Ambedkar and Mahatma Gandhi.", "True"],
    ["The INA trials took place in the Red Fort, Delhi.", "True"],
    ["The Khilafat Movement was supported by Mahatma Gandhi.", "True"],
    ["The Simon Commission was welcomed with black flags in India.", "True"],
    ["Ram Prasad Bismil was one of the leaders of the Kakori conspiracy.", "True"],
    ["India’s national song 'Vande Mataram' was written by Bankim Chandra Chattopadhyay.", "True"],
    ["Swaraj Party was founded in 1923.", "True"],
    ["Lal Bahadur Shastri gave the slogan 'Jai Jawan Jai Kisan'.", "True"],
    ["Raja Ram Mohan Roy founded the Brahmo Samaj.", "True"],
    ["Annie Besant started the Home Rule Movement in India.", "True"],
    ["The Champaran Satyagraha of 1917 was Gandhi's first movement in India.", "True"],
    ["Mangal Pandey was a key figure in the Revolt of 1857.", "True"],
    ["India was under British rule for more than 200 years.", "True"],
    ["Rajendra Prasad was the first President of India.", "True"],
    ["The Salt Satyagraha was also known as the Dandi March.", "True"],
    ["India’s independence was announced on 15th August 1947.", "True"],
    ["The slogan 'Do or Die' was given by Mahatma Gandhi.", "True"]
]
cs_questions = [
    ["Pointers were not used in the original C programming language; they were added later on in C++.", "False"],
    ["DHCP stands for Dynamic Host Configuration Port.", "False"],
    ["The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.", "False"],
    ["The programming language 'Python' is based off a modified version of 'JavaScript'.", "False"],
    ["Early RAM was directly seated onto the motherboard and could not be easily removed.", "True"],
    ["RAM stands for Random Access Memory.", "True"],
    ["The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.", "True"],
    ["Time on Computers is measured via the EPOX System.", "False"],
    ["A Mac is not a PC.", "False"],
    ["The HTML5 standard was published in 2014.", "True"],
    ["The open source program Redis is a relational database server.", "False"],
    ["The last Windows operating system to be based on the Windows 9x kernel was Windows 98.", "False"],
    ["In most programming languages, the operator ++ is equivalent to the statement '+= 1'.", "True"],
    ["A Boolean value of '0' represents which of these words?", "False"],
    ["The logo for Snapchat is a Bell.", "False"],
    ["All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.", "False"],
    ["The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.", "False"],
    ["The common software-programming acronym 'I18N' comes from the term 'Interlocalization'.", "False"],
    ["MacOS is based on Linux.", "False"],
    ["The 'Raspberry Pi' series of single-board computers were created in the United States.", "False"],
    ["The Windows ME operating system was released in the year 2000.", "True"],
    ["JavaScript derives from a later version of Java.", "False"],
    ["The Windows 7 operating system has six main editions.", "True"],
    ["Android versions are named in alphabetical order.", "True"],
    ["To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form.", "True"],
    ["FLAC stands for 'Free Lossless Audio Condenser'.", "False"],
    ["Linus Torvalds created Linux and Git.", "True"],
    ["The Python programming language gets its name from the British comedy group 'Monty Python.'", "True"],
    ["The first dual-core CPU was the Intel Pentium D.", "False"],
    ["'Windows NT' is a monolithic kernel.", "False"],

    # Extra 20 Questions added:
    ["HTML stands for HyperText Markup Language.", "True"],
    ["The C programming language was developed by Dennis Ritchie at Bell Labs.", "True"],
    ["Binary code uses only the digits 0 and 2.", "False"],
    ["The term 'GUI' stands for General User Interaction.", "False"],
    ["The IP address '127.0.0.1' refers to the local host (your computer).", "True"],
    ["Python is a statically typed programming language.", "False"],
    ["SQL is used for managing data in relational databases.", "True"],
    ["The first computer virus was created in the 2000s.", "False"],
    ["Linux is an example of open-source software.", "True"],
    ["IPv6 addresses are 128 bits long.", "True"],
    ["Machine learning is a branch of Artificial Intelligence.", "True"],
    ["CSS is used to add interactivity to web pages.", "False"],
    ["Moore's Law predicts that the number of transistors in a microchip doubles about every 2 years.", "True"],
    ["TCP stands for Transmission Control Protocol.", "True"],
    ["The 'cd' command in Linux is used to create a new directory.", "False"],
    ["Python supports multiple programming paradigms including object-oriented programming.", "True"],
    ["The World Wide Web and the Internet are exactly the same thing.", "False"],
    ["GPU stands for General Processing Unit.", "False"],
    ["The first version of Windows was released in 1985.", "True"],
    ["An algorithm is a step-by-step procedure for solving a problem.", "True"]
]
mythology_questions = [
    ["Lord Rama was the son of King Dasharatha.", "True"],
    ["The Mahabharata was written by Valmiki.", "False"],
    ["The Bhagavad Gita is part of the Mahabharata.", "True"],
    ["Lord Krishna was born in Mathura.", "True"],
    ["Hanuman is considered the son of Vayu (wind god).", "True"],
    ["Lord Shiva is also called 'Neelkanth'.", "True"],
    ["The Ramayana has 7 Kandas (books).", "True"],
    ["Karna was the eldest son of Kunti.", "True"],
    ["Goddess Saraswati is the goddess of wisdom and knowledge.", "True"],
    ["The Sudarshan Chakra is the weapon of Lord Vishnu.", "True"],
    ["Arjuna was the brother of Karna.", "True"],
    ["The Pandavas had five brothers.", "True"],
    ["Ravana had ten heads.", "True"],
    ["Goddess Durga killed Mahishasura.", "True"],
    ["Bhishma had the boon of choosing the time of his death.", "True"],
    ["The Kurukshetra war lasted for 18 days.", "True"],
    ["Shiva is worshipped in the form of Shivlinga.", "True"],
    ["Sita was the daughter of King Janaka.", "True"],
    ["Kumbhakarna was the brother of Ravana.", "True"],
    ["The Samudra Manthan produced Amrit and the deadly poison Halahala.", "True"],
    ["Lord Krishna lifted the Govardhan mountain.", "True"],
    ["The monkey army helped Lord Rama in the Ramayana.", "True"],
    ["Lord Ganesha has two wives named Riddhi and Siddhi.", "True"],
    ["The bow of Lord Shiva was called 'Pinaka'.", "True"],
    ["Bhima was the strongest among the Pandavas.", "True"],
    ["Shakuni was the maternal uncle of the Kauravas.", "True"],
    ["Lord Vishnu has ten avatars known as Dashavatara.", "True"],
    ["Abhimanyu was the son of Bhima.", "False"],
    ["Draupadi was married to all five Pandavas.", "True"],
    ["The river Ganga flows from the feet of Lord Vishnu.", "True"],
    ["Parashurama is considered the 6th avatar of Vishnu.", "True"],
    ["Goddess Lakshmi emerged during Samudra Manthan.", "True"],
    ["Lord Rama killed Bali by hiding behind a tree.", "True"],
    ["Bhima killed Duryodhana by striking his thigh.", "True"],
    ["Arjuna’s bow was named Gandiva.", "True"],
    ["Hanuman carried the Sanjeevani mountain.", "True"],
    ["Lord Vishnu rests on the serpent Sheshnag.", "True"],
    ["The demon Putana was killed by baby Krishna.", "True"],
    ["Shiva is also called 'Mahadeva'.", "True"],
    ["The epic Ramayana was written by Valmiki.", "True"],
    ["The demon king Hiranyakashipu was killed by Lord Narasimha.", "True"],
    ["Balarama was the elder brother of Krishna.", "True"],
    ["Ashwatthama was the son of Dronacharya.", "True"],
    ["The Kurukshetra war was fought between Pandavas and Kauravas.", "True"],
    ["Lord Krishna was killed by the hunter Jara.", "True"],
    ["The Mahabharata war was fought for the throne of Hastinapur.", "True"],
    ["Goddess Kali is a fierce form of Goddess Parvati.", "True"],
    ["Lord Rama’s kingdom was called Ayodhya.", "True"],
    ["The weapon 'Trishul' belongs to Lord Vishnu.", "False"],
    ["The Sun God is known as Surya.", "True"]
]
programming_questions = [
    ["Python was created by Guido van Rossum.", "True"],
    ["C was created by James Gosling.", "False"],
    ["C++ was developed by Bjarne Stroustrup.", "True"],
    ["Java was originally created by Microsoft.", "False"],
    ["The creator of Linux is Linus Torvalds.", "True"],
    ["HTML stands for HighText Machine Language.", "False"],
    ["CSS stands for Cascading Style Sheets.", "True"],
    ["In Python, 'print()' is used to display output.", "True"],
    ["In C, 'scanf' is used for output.", "False"],
    ["The symbol '//' is used for comments in C++.", "True"],
    ["In Python, '/* ... */' is used for comments.", "False"],
    ["JavaScript was created by Brendan Eich.", "True"],
    ["PHP was created by Larry Page.", "False"],
    ["The SQL command 'SELECT' is used to retrieve data.", "True"],
    ["In SQL, 'UPDATE' command deletes a table.", "False"],
    ["In Python, '==' is used for comparison.", "True"],
    ["In C, '=' is used for comparison.", "False"],
    ["COBOL is mainly used in business and finance.", "True"],
    ["FORTRAN was developed after Python.", "False"],
    ["Python is a compiled language.", "False"],
    ["Java is a platform-independent language.", "True"],
    ["The first computer programmer was Ada Lovelace.", "True"],
    ["Assembly language is a high-level language.", "False"],
    ["The command 'mkdir' creates a new directory in Linux.", "True"],
    ["The Linux command 'rm' is used to rename files.", "False"],
    ["In Python, 'len()' gives the length of a list.", "True"],
    ["C was developed at Bell Labs.", "True"],
    ["The symbol '&&' means logical OR in C.", "False"],
    ["The operator '||' means logical OR in C.", "True"],
    ["In Java, 'public static void main' is the entry point of a program.", "True"],
    ["In C, arrays start with index 1.", "False"],
    ["In Python, lists are mutable.", "True"],
    ["In C++, classes do not exist.", "False"],
    ["JavaScript runs only on servers.", "False"],
    ["Python supports both functional and object-oriented programming.", "True"],
    ["The '.py' extension is used for Python files.", "True"],
    ["The '.java' extension is used for C files.", "False"],
    ["The '.cpp' extension is used for C++ files.", "True"],
    ["In HTML, '<h1>' is the largest heading.", "True"],
    ["In HTML, '<p>' is used to display images.", "False"],
    ["In CSS, 'color' sets text color.", "True"],
    ["In CSS, 'border' sets background color.", "False"],
    ["Git was created by Linus Torvalds.", "True"],
    ["The command 'git clone' deletes a repository.", "False"],
    ["The command 'git push' uploads code to a repository.", "True"],
    ["In Python, indentation is required for code blocks.", "True"],
    ["In C, 'scanf' is used for input.", "True"],
    ["SQL stands for Sequential Query Language.", "False"],
    ["BASIC is an early beginner programming language.", "True"],
    ["Pascal programming language was named after a mathematician.", "True"],
    ["In Java, JVM stands for Java Virtual Machine.", "True"]
]
